### ISSUE TITLE
mr_ivw heterogeneity test does not calculate a Cochran Q statistic 

### ISSUE THREAD

**Issue by perezja** [MRCIEU/TwoSampleMR#125]
Hello authors,

I am wondering why the Cochran Q statistic calculation is commented out in the ‘mv_ivw’ method for heterogeneity tests performed by ‘mr_hetergeneity’. The function header comments explain that it is giving a multiplicative random effects estimate, but the calculation for Q and the exact test for heterogeneity which is being conducted seems poorly documented and the two references (21, 22) (the first of which I couldn’t access because there appears to be no electronic copy for this 1999 publication) in the TwosampleMR Base eLife paper does not seem to explain the method. What heterogeneity test is being applied and why is Cochran’s Q test appear to be deprecated?

**Comment by explodecomputer** [comment]
Hi @perezja 
Thanks for the message. Basically these two are equivalent

```
Q <- ivw.res$sigma^2 * Q_df
Q <- sum((1/(se_out/b_exp)^2)*(b_out/b_exp-b)^2)
```

The direct calculation was left in there for reference, which isn't necessarily good coding practice but there it is. It's commented out because the sigma is already calculated so no need to add to the computational load.

I'll update the documentation when I get a chance but basically

- mr_ivw_fe = fixed effects model
- mr_ivw_mre = multiplicative random effects model
- mr_ivw = multiplicative random effects model, with the modification that if the residual standard deviation (sigma) is greater than 1 then the standard error of the estimate is scaled to the fixed effects model. This prevents the random effects model giving a smaller standard error than the fixed effects model.

Have a look at this paper if you'd like to see Q being derived, and it might link to a more accessible earlier paper

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5434863/

**Comment by perezja** [comment]
Thank you for your reply. Much appreciated.
