### ISSUE TITLE
mr_steiger pvalues all 0

### ISSUE THREAD

**Issue by HannahVMeyer** [MRCIEU/TwoSampleMR#128]
Thanks for a great package!

I've noticed that running `mr_steiger` on any of my data results in pvalues=0. I am suspecting this is due to the number of significant digits returned and/or numerical instability when estimating r2 from n and p?

For instance for the following variables, where `p_exp` are pvalues from our study and `p_out` as downloaded via MRbase access:

```r
p_exp <- c(3.132564e-08, 1.682674e-11, 1.663413e-16, 1.114295e-11, 4.921528e-08, 1.071026e-08, 3.396253e-11, 1.963360e-16, 5.093309e-11, 4.315191e-20)
p_out <- c(1.33899e-01, 3.51114e-01, 2.16490e-02, 6.21642e-15, 3.91174e-02, 2.72023e-01, 4.67107e-01, 1.64812e-01, 6.15516e-02, 7.50593e-02)
n_exp <- c(18097, 18097, 18097, 18097, 18097, 18097, 18097, 18097, 18097, 18097)
n_out <- c(317754, 317754, 317754, 317754, 317754, 317754, 317754, 317754, 317754, 317754)
```

I get:
```r
snp_r2.exposure snp_r2.outcome correct_causal_direction steiger_pval
 0.02711903   2.637289e-04                     TRUE            0
```

Trying to track this down, it seems like there might be an option to add the number of digits returned by `psych::rtest` which is called from `mr_steiger`? In any case, I think it would be useful to at least return a `p < something` instead of 0 which is not correct.

```r
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         lattice_0.20-38    tidyr_1.0.0        prettyunits_1.0.2  ps_1.3.0           assertthat_0.2.1   zeallot_0.1.0      rprojroot_1.3-2    digest_0.6.21     
[10] psych_1.8.12       R6_2.4.0           plyr_1.8.4         backports_1.1.5    httr_1.4.1         ggplot2_3.2.1      pillar_1.4.2       rlang_0.4.0        curl_4.2          
[19] lazyeval_0.2.2     rstudioapi_0.10    data.table_1.12.2  TwoSampleMR_0.4.25 googleAuthR_0.8.1  callr_3.3.2        desc_1.2.0         labeling_0.3       devtools_2.2.1    
[28] stringr_1.4.0      foreign_0.8-71     munsell_0.5.0      xfun_0.9           compiler_3.6.1     pkgconfig_2.0.3    mnormt_1.5-5       pkgbuild_1.0.5     papaja_0.1.0.9842 
[37] tidyselect_0.2.5   tibble_2.1.3       gridExtra_2.3      roxygen2_6.1.1     crayon_1.3.4       dplyr_0.8.3        withr_2.1.2        commonmark_1.7     grid_3.6.1        
[46] nlme_3.1-140       jsonlite_1.6       gtable_0.3.0       lifecycle_0.1.0    magrittr_1.5       modules_0.9.11     scales_1.0.0       cli_1.1.0          stringi_1.4.3     
[55] reshape2_1.4.3     fs_1.3.1           remotes_2.1.0      getopt_1.20.3      testthat_2.2.1     optparse_1.6.4     xml2_1.2.2         plinkQC_0.2.3      ellipsis_0.3.0    
[64] vctrs_0.2.0        cowplot_1.0.0      tools_3.6.1        glue_1.3.1         purrr_0.3.2        processx_3.4.1     pkgload_1.0.2      parallel_3.6.1     colorspace_1.4-1  
[73] UpSetR_1.4.0       sessioninfo_1.1.1  memoise_1.1.0      knitr_1.25         egg_0.4.5          usethis_1.5.1     
```

**Comment by explodecomputer** [comment]
Hi @HannahVMeyer thanks for this and for looking at it in detail

I think when the p-value is less then 1e-300 or something it just gets a numerical precision problem and rounds to 0. It's using the pnorm function to get the p-value, and in the docymentation is shows how to use the print function to reduce the number of digits.

I'm not sure what else can be done really, but in terms of reporting you could just put p < 2e-16 or something which is a standard precision threshold that R functions spit out sometimes? 

Also, just to mention in case it's helpful, if making a strong interpretation of the r2 differences in exposure and outcome just make sure that the snp-exposure effects are from a replication sample as winner's curse will bias the r2 upwards

**Comment by HannahVMeyer** [comment]
Thanks for getting back so quickly, I thought the precision might be at the bottom of it. 

I opened the issue, wondering if it might be worthwhile to include return the `mr_steiger` pvalues enclosed in a print statement with max number of digits? Or add a comment to the documentation why 0 pvalues can arise or that  they should be treated like `p < 2e-16` or something.

Thanks for the heads up about the winner's curse bias - there might be some sample overlap, but we cannot be sure. We calculate the F statistic and lower bound on F parameter to get an estimate for weak instrument bias and potential winners curse. Does that seem alright?

**Comment by explodecomputer** [comment]
Sure I can add something to the documentation, though the issue is present in basically all statistical tests in R and it's not common to see that kind of warning. 

Wrt winner's curse I was thinking about it not in terms of weak instrument bias, but the steiger directionality test. The r2_snp_exposure and r2_snp_outcome are compared, where r2_snp_exposure is likely inflated due to ascertainment on a threshold but r2_snp_outcome is in principle not ascertained due to a threshold, so r2_snp_exposure is likely to be higher. Ideally an estimate of r2_snp_exposure would be obtained from a replication sample, where it will likely be lower than the discovery sample

**Comment by remlapmot** [comment]
It’s perhaps worth adding that the way the p-value is coded can affect at what *z*-statistic R starts reporting 0.

For example, for the following 2 ways R prints the same p-value.

``` r
2 * pnorm(-1 * 1.96)
#> [1] 0.04999579
2 * (1 - pnorm(1.96))
#> [1] 0.04999579
```

However for larger values of *z* R starts reporting 0 for the second method.

``` r
2 * pnorm(-1 * 8.3)
#> [1] 1.041114e-16
2 * (1 - pnorm(8.3))
#> [1] 0
```

I think this is because this p-value is less than `.Machine$double.eps / 2` and so R cannot do the `1 - #` part of the calculation anymore.

The first way will give p-values down to `.Machine$double.xmin`=2.225073910^{-308} (in the region of *z*=37.5ish).

``` r
# one-sided p-value
pnorm(-1 * 37.5)
#> [1] 4.605353e-308
```

The helpfile for `.Machine`, `?.Machine`, has info about the limits of the machine you’re using.
<sup>Created on 2019-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by HannahVMeyer** [comment]
Yes, indeed. For the example above, running `mr_steiger` in debug mode and manually testing 
`2 * pnorm(-1 * z)`
yields
`1.051919e-85`. Which as you were saying before is `p << 2e-16`. 
Thanks both for your comments!

**Comment by explodecomputer** [comment]
Thanks very much both it turns out this is what is happening in the `psych::r.test` function

https://github.com/cran/psych/blob/master/R/r.test.R#L51

I updated the all instances of `psych::r.test` to use `pnorm(-abs(z)) * 2` instead of the p-value. 

Commit is here: f7599b2

I acknowledged you both in the NEWS file hope that's ok, this isn't a new release but will be carried forward then
