### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by shantanubafna** [MRCIEU/TwoSampleMR#162]
Hi, 

I update the package again because I found different results every time for an analysis run for a set of IDs. Now I'm not able to even extract the instruments or even download the previous or the new package.

**devtools::install_github("MRCIEU/TwoSampleMR")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 146.203.130.213. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2020-02-14 16:47:40 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`**

**Comment by explodecomputer** [comment]
hey sorry about this. there are two separate things happening

1. there have been a few issues with the new version 0.5.0 and the new database. We've fixed most of them, and have temporarily disabled some datasets that are still needed to be fixed. If you update to 0.5.1 there is info about it in the news file
2. For some reason this error you're reporting happens because of github's policy on the number of anonymous downloads. follow the instructions to increase your rate limit and it will work for you again
