### ISSUE TITLE
clump_data() gave different number of SNPs when re-running my analysis 

### ISSUE THREAD

**Issue by XiyunJiang** [MRCIEU/TwoSampleMR#189]
Dear TwoSampleMR team, 
First of all, I'd like to say a thank you for developing this amazing package to run 2SMR! but I do have a question. 
I ran a two-sample MR a few months ago using my own datasets for exposure and outcome, and I used clump_data() function to get independent SNPs and I got around 224 SNPs. I came back recently to reproduce my analysis (using exactly the same code and datasets) but only 219 SNPs came out as independent. I am very confused for this discrepancy, please can you provide some insight? Is this because of the recent change in LD reference panel ?? 

Thanks a lot 
Xiyun

**Comment by XiyunJiang** [comment]
For more information, I am using package version 0.5.1 and did not update my package.

**Comment by explodecomputer** [comment]
Hi @XiyunJiang 
Really sorry for the slow reply, thanks for letting me know about this.
The clumping dataset was recently updated on the API to accommodate multiple ancestral populations. This might have led to some slight differences in the European dataset. 

I'm reinstating the previous European dataset so that can be used as an option. e.g.

```
clump_data(dat, pop="legacy")
```

will use the previous LD reference panel
