### ISSUE TITLE
Clump_data() returning null

### ISSUE THREAD

**Issue by HayesB12** [MRCIEU/TwoSampleMR#194]
Hi, 

Yesterday and this morning i've found that when using the clump_data function, every SNP is being pruned, leaving me with an empty dat. 

I've reverted to an older version (MRCIEU/TwoSampleMR@0.4.26) and once i'd re-verified I was able to successfully use this function again. 

Just wanted to flag it

Thanks!

**Comment by mightyphil2000** [comment]
Hi could you post this on our github issues page?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZoheirAlayash** [comment]
Hello,
So I ran this  "devtools::install_github("MRCIEU/TwoSampleMR@0.4.26")" ,but still it is giving me this error message " Error in ieugwasr::ld_clump(d, clump_kb = clump_kb, clump_r2 = clump_r2,  : 
  unused argument (pop = pop)". 
Any tips??

**Comment by chunyu-yes** [comment]
Hello,
I met the same question.

**Comment by zaynemilena** [comment]
Hello everyone,

I have the same problem. clump_data function was working perfectly last week but today it is leaving me with empty data.
This is my error message:
Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001
Clumping GG2TE7, 2941 variants, using EUR population reference
Removing 2941 of 2941 variants due to LD with other variants or absence from LD reference panel

**Comment by explodecomputer** [comment]
We had a huge amount of traffic that was paralysing multiple services so we had to disable this feature for a little while. Sorry about that, it's back up now and hopefully won't come under severe load again.

One important note: if you are doing a large amount of LD operations please do it locally rather than through the API, e.g. see here for instructions, we tried to make it as seamless as possible to do this: https://mrcieu.github.io/ieugwasr/articles/local_ld.html

Thanks all, sorry again for the inconvenience
