### ISSUE TITLE
Server code: 503; Server is possibly experiencing traffic, trying again...

### ISSUE THREAD

**Issue by Amanda2018genetics** [MRCIEU/TwoSampleMR#201]
Hi all，

Have you got this error before when using extract_instruments function to extract instruments from datasets like
  `ukbb_inst <- extract_instruments(ukbb_id,
                                 p1=5e-06,
                                 clump = TRUE,
                                 p2 = 5e-06,
                                 r2 = 0.001,
                                 kb = 10000)`

The error：

`Server code: 503; Server is possibly experiencing traffic, trying again...`

I can use the same function a few days before. 
Hope anyone can help with me, appreciated.

Best,
Yao

**Comment by PandaPowell** [comment]
Hello,

yes I am experiencing the same issue when running the extract_outcomes function. 

The function attempts to find proxies then the same server code error message appears and the proxies are not extracted, however the rest of the snps are.

**Comment by explodecomputer** [comment]
I think maybe the message about trying again is creating confusion here - If you are retrieving results then the retry succeeded. I have just updated so that if it says it's retrying it will then report whether it ultimately succeeds or fails. Generally speaking if you actually did get a table of results then it completed as expected. The lack of proxies would ostensibly mean that it just didn't find any. But if it returned httr object with an error status code then the query has failed
