### ISSUE TITLE
Wald ratio p value is too small

### ISSUE THREAD

**Issue by kaanokay** [MRCIEU/TwoSampleMR#228]
Hi,

First of all, I would like to thank you for this nice R package.

I performed MR analysis for GWAS data and then obtained a single SNP with the Wald ratio, but p-value of this Wald ratio is 0.
Is obtaining of such too small a p-value problem? However, the MR-RAPS estimate of the same SNP has 3.72e-11 p-value. I want to put these Wald ratio and MR-RAPS results in my article, so I want to be sure about this situation is problematic or not?

Thanks for your response.

Best regards.

**Comment by mightyphil2000** [comment]
Hi Kaan

I think when the P value is very tiny (I think < 1e-300) the function will return a zero.

I recommend you try to recalculate the P value using the Z score, which is b/se (corresponding to the Wald ratio effect estimate and it's standard error).

For example, a Z score of 1.96 corresponds to a two sided P value of 0.05 and can be found using pnorm function in R:

pnorm(1.96,lower.tail=F)*2


bw
philip


________________________________

**Comment by kaanokay** [comment]
Dear Philip,

I figured out this issuse.

Thanks for your detailed and clear answer.

Best regards.

**Comment by Hugolyu** [comment]
> Dear Philip,
> 
> I figured out this issuse.
> 
> Thanks for your detailed and clear answer.
> 
> Best regards.

Dear Kaanokay

I encountered the same problem as you when performing MR analysis. I obtained a single SNP with the Wald ratio, but the p-value of this Wald ratio is 0. I also tried to extract the SNP from the MRbase web platform, and I still obtained a p-value of zero. is that suggests  the issue might be due to the exposure GWAS data?  Could you kindly provide some guidance on how to resolve this issue?

Best regards
 

Hugo lyu
