### ISSUE TITLE
error about mr_heterogeneity

### ISSUE THREAD

**Issue by SeanZhi** [MRCIEU/TwoSampleMR#239]
hello!
I follow the guideline step by step，
when I run "het<-mr_heterogeneity(my_eur_res)"，
an error has occurred:"Error in eval(e, x, parent.frame()) : object 'mr_keep' not found"
any suggestions?

**Comment by mightyphil2000** [comment]
Make sure the data is in the correct format. These kinds of errors are often due to errors in data formatting. Can you paste all your code?

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: SeanZhi <notifications@github.com>
Enviado: Friday, December 4, 2020 9:28:09 AM
Para: MRCIEU/TwoSampleMR <TwoSampleMR@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [MRCIEU/TwoSampleMR] error about mr_heterogeneity (#239)


hello!
I follow the guideline step by step，
when I run "het<-mr_heterogeneity(my_eur_res)"，
an error has occurred:"Error in eval(e, x, parent.frame()) : object 'mr_keep' not found"
any suggestions?

**Comment by SeanZhi** [comment]
thanks for your reply
I found the reason. I was careless. The input of "mr_heterogeneity" is " mydata", not the output of "mr(mydata)". Thanks again.
