### ISSUE TITLE
issues with installing the pkg

### ISSUE THREAD

**Issue by MoMaz123** [MRCIEU/TwoSampleMR#245]
Hi, I am running as a below, would you please advise why I can't get the pkg on my Rstudio.
Many thanks in advance!

devtools::install_github("MRCIEU/TwoSampleMR",dependencies = FALSE)
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 94.193.192.225. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2021-01-18 11:30:41 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

**Comment by MoMaz123** [comment]
it's been solved, thanks anyway

**Comment by QianwenLiustats** [comment]
Hi 
I am having the same problem, could you share how you solved the problem?

**Comment by explodecomputer** [comment]
Hey @QianwenLiustats you basically just have to follow the instructions:

- Use `usethis::browse_github_pat()` to create a Personal Access Token.
- Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

Basically it will tell github that the download is from a real account, because when it gets downloaded a lot then it thinks it might be a bot
