### ISSUE TITLE
Running huge number of test

### ISSUE THREAD

**Issue by amaa11** [MRCIEU/TwoSampleMR#269]
Dear all,
Thanks for the nice package.
I use it on my local PC.
I wonder if I can run and use the package in a parallel way?
I mean I might need to run around 90 million MR associations.
Is it possible to run it using parallel processing ? otherwise it is very much time consuming.
If it is possible, any idea?
Best regards

**Comment by t0mrg** [comment]
If you are using data from the OpenGWAS database we ask you to avoid too many parallel queries (which will overload the API and reduce performance for other users). Highly parallel analyses should be performed by downloading the VCF files from the OpenGWAS database and analysing them locally (rather than through the API).
