### ISSUE TITLE
What is difference between odds ratio and beta coefficient?

### ISSUE THREAD

**Issue by kaanokay** [MRCIEU/TwoSampleMR#283]
### Discussed in https://github.com/MRCIEU/TwoSampleMR/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **kaanokay** July  8, 2021</sup>
Hi,

First of all, I'd like to thank you for this amazing tool.

I have a question about odds ratio and beta coefficient usage during TwoSampleMR analysis. I have two case-control GWAS data sets. A GWAS data has odds ratio, but other has beta-coefficient. I want to perform bi-directional MR analysis for two datasets. Do I need to convert odds ratio and its standard error to beta coefficient and its standard error for bidirectional analysis? Or, can I use odds ratio for a data and beta coefficient for other data without any conversion? If I make analysis without conversion of odds ratio to beta values, is this a problem? Does it effect my results?

Thank you for your help and interest.
Best regards.</div>

**Comment by mightyphil2000** [comment]
Hi Kaanokay
I recommend you convert the odds ratios to log odds ratios. For the other case-control GWAS containing beta coefficients, if the results were generated in a logistic regression model the beta coefficients will most likely be log odds ratios. 

I would leave the standard errors as they are. The standard errors you already have are mostly likely standard errors for the log odds ratios. Standard errors aren't defined for odds ratios due to their asymmetric distribution.

**Comment by kaanokay** [comment]
@mightyphil2000 thank you so much for your quick reply.

Best.
