### ISSUE TITLE
Error when attempting to update to v0.4.9

### ISSUE THREAD

**Issue by DCousminer** [MRCIEU/TwoSampleMR#30]
I have successfully used the TwoSampleMR package many times, but today I am having an issue after attempting to update with devtools::install_github('MRCIEU/TwoSampleMR'). 

ERROR: dependency 'httpuv' is not available for package 'TwoSampleMR'

I installed httpuv with install.packages("httpuv") but the problem remained.

**Comment by DCousminer** [comment]
This seems to result in a problem when I get to the harmonization stage:

>dat <- harmonise_data(exposure_dat, outcome_dat_filtered, action = 1)
Error in FUN(X[[i]], ...) : object 'id.exposure' not found

**Comment by mightyphil2000** [comment]
Hey


Did you restart R and reload the library? Does that help?


Can you send the full code so we can reproduce the analysis?



________________________________

**Comment by DCousminer** [comment]
After restarting and reinstalling 'TwoSampleMR' it appeared there were no errors, but then I still get the same error at the harmonization step.

>exposure_dat <- extract_instruments(outcomes= 1095)
>outcome_dat <- extract_outcome_data(snps=exposure_dat$SNP, outcomes= 89)
>outcome_dat <- clump_data(outcome_dat)
>sort<-outcome_dat[order(outcome_dat$pval.outcome),]
>outcome_dat_filtered<-outcome_dat[outcome_dat$pval.outcome> 0.0007352,]
>dat <- harmonise_data(exposure_dat, outcome_dat_filtered, action = 2)

Error in FUN(X[[i]], ...) : object 'id.exposure' not found

**Comment by mightyphil2000** [comment]
Sounds like you excluded your exposure SNPs from the outcome data.

Philip Haycock, PhD
MR-Base: www.mrbase.org
CRUK Population Research Fellow
MRC Integrative Epidemiology Unit
University of Bristol
Oakfield House, Oakfield Grove
Bristol, BS8 2BN, UK
T +44 (0)117 3310088
________________________________

**Comment by DCousminer** [comment]
There are 44 SNPs remaining after the p-value filter.

**Comment by DCousminer** [comment]
> head(exposure_dat)
     id.exposure        SNP effect_allele.exposure other_allele.exposure eaf.exposure beta.exposure
1093        1095  rs1516883                      a                     g         0.30        -0.091
1094        1095   rs466639                      t                     c         0.13        -0.075
1095        1095  rs1079866                      c                     g         0.88        -0.072
1096        1095 rs16938437                      t                     c         0.05        -0.067
1097        1095 rs12291726                      a                     g         0.89        -0.057
1098        1095 rs12148769                      a                     g         0.12        -0.055
     se.exposure pval.exposure samplesize.exposure ncase.exposure ncontrol.exposure units.exposure
1093 0.002455094       0.0e+00              182416             NA                NA          years
1094 0.008705842       7.0e-18              182416             NA                NA          years
1095 0.008443620       1.5e-17              182416             NA                NA          years
1096 0.010347969       9.5e-11              182416             NA                NA          years
1097 0.008332907       7.9e-12              182416             NA                NA          years
1098 0.009751685       1.7e-08              182416             NA                NA          years
                       exposure pval_origin.exposure data_source.exposure mr_keep.exposure
1093 Age at menarche || id:1095             reported               mrbase             TRUE
1094 Age at menarche || id:1095             reported               mrbase             TRUE
1095 Age at menarche || id:1095             reported               mrbase             TRUE
1096 Age at menarche || id:1095             reported               mrbase             TRUE
1097 Age at menarche || id:1095             reported               mrbase             TRUE
1098 Age at menarche || id:1095             reported               mrbase             TRUE


> head(outcome_dat_filtered)
         SNP beta.outcome se.outcome samplesize.outcome ncase.outcome ncontrol.outcome pval.outcome
1  rs7119712      -0.0066     0.0033             253131            NA               NA        0.045
2  rs7103411      -0.0034     0.0036             253238            NA               NA        0.340
4 rs10840031       0.0063     0.0032             249730            NA               NA        0.052
6  rs3870341      -0.0054     0.0033             252807            NA               NA        0.100
8  rs1874984       0.0065     0.0031             245572            NA               NA        0.038
9  rs2836950       0.0080     0.0032             246092            NA               NA        0.013
  eaf.outcome effect_allele.outcome other_allele.outcome units.outcome         outcome
1       0.192                     A                    G        SD (m) Height || id:89
2       0.780                     T                    C        SD (m) Height || id:89
4       0.242                     A                    G        SD (m) Height || id:89
6       0.305                     A                    G        SD (m) Height || id:89
8       0.442                     C                    G        SD (m) Height || id:89
9       0.686                     C                    G        SD (m) Height || id:89
  consortium.outcome year.outcome pmid.outcome id.outcome category.outcome subcategory.outcome
1              GIANT         2014     25282103         89      Risk factor      Anthropometric
2              GIANT         2014     25282103         89      Risk factor      Anthropometric
4              GIANT         2014     25282103         89      Risk factor      Anthropometric
6              GIANT         2014     25282103         89      Risk factor      Anthropometric
8              GIANT         2014     25282103         89      Risk factor      Anthropometric
9              GIANT         2014     25282103         89      Risk factor      Anthropometric
  originalname.outcome      outcome.deprecated mr_keep.outcome data_source.outcome pval.exposure
1               Height Height || GIANT || 2014            TRUE              mrbase          0.99
2               Height Height || GIANT || 2014            TRUE              mrbase          0.99
4               Height Height || GIANT || 2014            TRUE              mrbase          0.99
6               Height Height || GIANT || 2014            TRUE              mrbase          0.99
8               Height Height || GIANT || 2014            TRUE              mrbase          0.99
9               Height Height || GIANT || 2014            TRUE              mrbase          0.99
  id.exposure
1      QrYyTK
2      QrYyTK
4      QrYyTK
6      QrYyTK
8      QrYyTK
9      QrYyTK

**Comment by explodecomputer** [comment]
Hey I think remove or rename the id.exposure column from the
outcome_dat_filtered object, this will cause issues after the merge




On 22 May 2018 at 15:28:20, DCousminer (notifications@github.com) wrote:

head(exposure_dat)
id.exposure SNP effect_allele.exposure other_allele.exposure eaf.exposure
beta.exposure
1093 1095 rs1516883 a g 0.30 -0.091
1094 1095 rs466639 t c 0.13 -0.075
1095 1095 rs1079866 c g 0.88 -0.072
1096 1095 rs16938437 t c 0.05 -0.067
1097 1095 rs12291726 a g 0.89 -0.057
1098 1095 rs12148769 a g 0.12 -0.055
se.exposure pval.exposure samplesize.exposure ncase.exposure
ncontrol.exposure units.exposure
1093 0.002455094 0.0e+00 182416 NA NA years
1094 0.008705842 7.0e-18 182416 NA NA years
1095 0.008443620 1.5e-17 182416 NA NA years
1096 0.010347969 9.5e-11 182416 NA NA years
1097 0.008332907 7.9e-12 182416 NA NA years
1098 0.009751685 1.7e-08 182416 NA NA years
exposure pval_origin.exposure data_source.exposure mr_keep.exposure
1093 Age at menarche || id:1095 reported mrbase TRUE
1094 Age at menarche || id:1095 reported mrbase TRUE
1095 Age at menarche || id:1095 reported mrbase TRUE
1096 Age at menarche || id:1095 reported mrbase TRUE
1097 Age at menarche || id:1095 reported mrbase TRUE
1098 Age at menarche || id:1095 reported mrbase TRUE

head(outcome_dat_filtered)
SNP beta.outcome se.outcome samplesize.outcome ncase.outcome
ncontrol.outcome pval.outcome
1 rs7119712 -0.0066 0.0033 253131 NA NA 0.045
2 rs7103411 -0.0034 0.0036 253238 NA NA 0.340
4 rs10840031 0.0063 0.0032 249730 NA NA 0.052
6 rs3870341 -0.0054 0.0033 252807 NA NA 0.100
8 rs1874984 0.0065 0.0031 245572 NA NA 0.038
9 rs2836950 0.0080 0.0032 246092 NA NA 0.013
eaf.outcome effect_allele.outcome other_allele.outcome units.outcome outcome
1 0.192 A G SD (m) Height || id:89
2 0.780 T C SD (m) Height || id:89
4 0.242 A G SD (m) Height || id:89
6 0.305 A G SD (m) Height || id:89
8 0.442 C G SD (m) Height || id:89
9 0.686 C G SD (m) Height || id:89
consortium.outcome year.outcome pmid.outcome id.outcome category.outcome
subcategory.outcome
1 GIANT 2014 25282103 89 Risk factor Anthropometric
2 GIANT 2014 25282103 89 Risk factor Anthropometric
4 GIANT 2014 25282103 89 Risk factor Anthropometric
6 GIANT 2014 25282103 89 Risk factor Anthropometric
8 GIANT 2014 25282103 89 Risk factor Anthropometric
9 GIANT 2014 25282103 89 Risk factor Anthropometric
originalname.outcome outcome.deprecated mr_keep.outcome data_source.outcome
pval.exposure
1 Height Height || GIANT || 2014 TRUE mrbase 0.99
2 Height Height || GIANT || 2014 TRUE mrbase 0.99
4 Height Height || GIANT || 2014 TRUE mrbase 0.99
6 Height Height || GIANT || 2014 TRUE mrbase 0.99
8 Height Height || GIANT || 2014 TRUE mrbase 0.99
9 Height Height || GIANT || 2014 TRUE mrbase 0.99
id.exposure
1 QrYyTK
2 QrYyTK
4 QrYyTK
6 QrYyTK
8 QrYyTK
9 QrYyTK

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MRCIEU/TwoSampleMR/issues/30#issuecomment-391011174>,
or mute the thread

**Comment by actright1** [comment]
The error is likely because you wrongly assigned the outcome data as the exposure data. Double check to be sure this is not the case.

**Comment by jessica-lundin-sage** [comment]
I had the same issue because of a column in my outcome file named id.exposure. This did the trick. Thanks!
