### ISSUE TITLE
can loops be used with two sample MR?

### ISSUE THREAD

**Issue by rskl92** [MRCIEU/TwoSampleMR#41]
Hi,

I want to read in several exposures using this code but it reports this error "Error in data.table::fread(filename, header = TRUE, sep = sep) : 
  'input' must be a single character string containing a file name, a command, full path to a file, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or the input data itself".
Hence, I was curious as to whether loops can't be used with this package or I've done something wrong!

> file.list <- dir(pattern='*_gws.txt.', recursive=TRUE)
> exposure_data <- lapply(file.list,read.delim)
> 
> for (i in 1:length(exposure_data)){
+     test_exp_dat <- read_exposure_data(
+         filename=exposure_data[i],
+         sep = "\t",
+         snp_col = "snp_col",
+         beta_col = "effect",
+         se_col = "SE",
+         #effect_allele_col = "a1",
+         #other_allele_col = "a2",
+         #eaf_col = "a1_freq",
+         #pval_col = "p-value",
+         #units_col = "Units",
+         #gene_col = "Gene",
+         #samplesize_col = "n"
+     )}

**Comment by mightyphil2000** [comment]
Hi


You could use a loop but that particular script won't work because you'd need to tell R that test_exp_dat is a list object. Anyway, it would be more efficient to have all your exposure summary data in a single file. Does each "*_gwas.txt" file correspond to a set of genetic instruments for a single exposure? I recommend you could combine these into a single file and then use read_exposure_data() to read that file. Then you can produce MR analyses for each exposure-outcome combination in that file.


If you wanted to use your code you'd have to modify it with something like this (but I don't recommend this because then you'll have to do more loops for all the downstream MR steps - not necessary if exposures are in a single file):


test_exp_dat<-NULL
for (i in 1:length(exposure_data)){
test_exp_dat[[i]] <- read_exposure_data(
...

________________________________

**Comment by stephen8624** [comment]
Thanks for your prompt response. If I had my exposures (there are a lot!) in a single file, would I need to edit each file and add a column to indicate the phenotype name beforehand and then merge them into a single file to input into exposure_data. .. Would the read_exposure_data be able to read the file even though I would have added a column which it doesn't use?

**Comment by rskl92** [comment]
Thanks for your prompt response. If I had my exposures (there are a lot!) in a single file, would I need to edit each file and add a column to indicate the phenotype name beforehand and then merge them into a single file to input into exposure_data. .. Would the read_exposure_data be able to read the file even though I would have added a column which it doesn't use?

**Comment by explodecomputer** [comment]
you could do something like:

```
library(dplyr)
l <- list()
for(i in filelist)
{
  l[[i]] <- read_exposure_data(filename=i, ...)
  l[[i]]$exposure <- i
}
exposure_dat <- bind_rows(l)
```

**Comment by rskl92** [comment]
Very helpful responses! Many thanks
