### ISSUE TITLE
[BUG]:  Failed to connect to api.github.com port 443 

### ISSUE THREAD

**Issue by liaofengnan** [MRCIEU/TwoSampleMR#465]
devtools::install_local('./TwoSampleMR.zip')
Wrong: Failed to install 'TwoSampleMR.zip' from local:
  Timeout was reached: [api.github.com] Failed to connect to api.github.com port 443 after 10001 ms: Timeout was reached

**Comment by remlapmot** [comment]
You can install TwoSampleMR from <https://mrcieu.r-universe.dev/builds> with

### Windows and Intel Macs

For Windows and Intel Mac users the installation code to obtain a binary version of **TwoSampleMR** is

```r
# Installation code for Windows and Intel Mac users
install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev',
    'https://cloud.r-project.org'
  )
)
```

### Ubuntu Jammy Jellyfish

For Ubuntu Jammy Jellyfish users running R through RStudio Desktop or RStudio Server the installation code is

```r
# Installation code for Ubuntu Jammy Jellyfish users in RStudio Desktop or Server
install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
```

For Ubuntu Jammy Jellyfish users running R in the Terminal first amend the `HTTPUserAgent` option, as described in the following blog [post](https://tshafer.com/blog/2023/07/posit-package-manager-linux), and then run the Linux installation code above. This is in order to obtain binary packages from the Posit Public Package Manager. If the `HTTPUserAgent` option is not amended it seems that source rather than binary packages are obtained for the Imports dependency packages. So for this case the full installation code is

```r
# Installation code for Ubuntu Jammy Jellyfish users running R in the Terminal
options(HTTPUserAgent = sprintf(
  "R/%s R (%s)",
  getRversion(),
  paste(getRversion(),
        R.version["platform"],
        R.version["arch"],
        R.version["os"])
))

install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
```

**Comment by liaofengnan** [comment]
Thank you for your help! It really work!



At 2024-01-10 03:36:40, "Tom Palmer" ***@***.***> wrote:

You can install TwoSampleMR from https://mrcieu.r-universe.dev/builds with

Windows and Intel Macs

For Windows and Intel Mac users the installation code to obtain a binary version of TwoSampleMR is

# Installation code for Windows and Intel Mac users
install.packages(
  'TwoSampleMR',
  repos= c(
    'https://mrcieu.r-universe.dev',
    'https://cloud.r-project.org'
  )
)
Ubuntu Jammy Jellyfish

For Ubuntu Jammy Jellyfish users running R through RStudio Desktop or RStudio Server the installation code is

# Installation code for Ubuntu Jammy Jellyfish users in RStudio Desktop or Server
install.packages(
  'TwoSampleMR',
  repos= c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)

For Ubuntu Jammy Jellyfish users running R in the Terminal first amend the HTTPUserAgent option, as described in the following blog post, and then run the Linux installation code above. This is in order to obtain binary packages from the Posit Public Package Manager. If the HTTPUserAgent option is not amended it seems that source rather than binary packages are obtained for the Imports dependency packages. So for this case the full installation code is

# Installation code for Ubuntu Jammy Jellyfish users running R in the Terminal
options(HTTPUserAgent= sprintf(
  "R/%s R (%s)",
  getRversion(),
  paste(getRversion(),
        R.version["platform"],
        R.version["arch"],
        R.version["os"])
))

install.packages(
  'TwoSampleMR',
  repos= c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
