### ISSUE TITLE
[BUG]:  Used up your OpenGWAS allowance

### ISSUE THREAD

**Issue by dongchaoanderuni** [MRCIEU/TwoSampleMR#538]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**
I generate OpenGWAS allowance and just use it by myself. But if even I reset the OpenGwas API. Write the new token into .Renviron. Restart my IDE, and run it again. Still have this problem in my console. I have no idea whether it is a bug or not. 

## Describe the bug (required)

*Provide a clear and concise description of what the bug is*

## Describe the current behaviour you observe (required)
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping ukb-a-275, 30716 variants, using EUR population reference
Warning in set_reset(r) :
  You have used up your OpenGWAS allowance. Your allowance will reset at 2024-07-20 15:06:48.696879. See https://api.opengwas.io/api/#allowance for more details.
No encoding supplied: defaulting to UTF-8.

Error in mtfrm.default(list(url = "https://api.opengwas.io/api/ld/clump",  (drugMR05.MR.R#28): cannot mtfrm
Show stack trace

*Include code blocks with any error messages*

## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by JasonQiu** [comment]
https://blog.opengwas.io/posts/user-auth-spring-2024/#your-allowance-and-the-costs

**Comment by dongchaoanderuni** [comment]
Thank you for your attention. I have  waited for several another times to use the token. But when I use it, even if there are 100, 000 Allowance on the website https://api.opengwas.io/profile/. But when I run the program, it just showed used up. So Could you please see it, if it is a Bug or not. It last more than three days. Thank you. Here is my IP: 97.64.19.239

**Comment by JasonQiu** [comment]
Please provide the `account_id` and your `ip` address which can be found in `ieugwasr::user()`. Do not post your names or email address.
Also make sure you are using the latest versions of ieugwasr and TwoSampleMR and have detached them before load().
What does `options()$ieugwasr_reset` say?

**Comment by dongchaoanderuni** [comment]
$user$account_id
[1] "2ed27968-9bfb-3283-990c-0bed1c2c7f8f"

$client$your_ip
[1] "114.222.73.123"

The result of: options()$ieugwasr_reset
NULL

Version of TwoSampleMR: 0.6.6
Version of ieugwasr: 1.0.1

Thank you for your attention. But I have no idea how to  detach ieugwasr and TwoSampleMR before load(), so for this one, I have no idea whether I use it in a proper way. 

```

library(TwoSampleMR)
library(ieugwasr)

outcomeID  <- "ieu-a-7"     #结局数据ID
exposureID <- "ieu-a-300"        #暴露数据ID

geneChr <-5#基因所在的染色体(https://www.ncbi.nlm.nih.gov/gene)
geneStart <-74692776 #染色体起始位置
geneEnd <-74645041#染色体终止位置

exposureName <- "LDL cholesterol || HMGCR"     #设置图形中展示暴露因素的名称
diseaseName <- "Coronary heart disease"        #疾病名称

setwd("E:\\A_Projects\\Rprojects\\P11_MedTargetMR\\05.MR")      #设置工作目录


exposure_dat <- extract_instruments(outcome = exposureID,
                                    clump = FALSE)


exposure_dat <- clump_data(exposure_dat, clump_kb=100,
                       clump_r2 = 0.3,
                       clump_p1 = 5e-08,
                       clump_p2 = 5e-08,
                       pop = "EUR")


geneData<-subset(exposure_dat, chr.exposure==geneChr & pos.exposure>(geneStart-offset) & pos.exposure<(geneEnd+offset))


geneData<-subset(geneData, eaf.exposure>0.01)


outcome_dat <- extract_outcome_data(snps=geneData$SNP, outcomes=outcomeID)


geneData$exposure <- exposureName
outcome_dat$outcome <- diseaseName


dat <- harmonise_data(geneData, outcome_dat)


outTab <- dat[dat$mr_keep=="TRUE",]


write.csv(outTab, file="table.SNP.csv", row.names=F)


presso <- run_mr_presso(dat)
write.csv(presso[[1]]$`MR-PRESSO results`$`Global Test`, file="table.MR-PRESSO_Global.csv")
write.csv(presso[[1]]$`MR-PRESSO results`$`Outlier Test`, file="table.MR-PRESSO_Outlier.csv")


mrResult <- mr(dat)

mrTab <- generate_odds_ratios(mrResult)

mrTab$orDrug <- 1/mrTab$or

beta <- log(mrTab$orDrug)

mrTab$or_lci95Drug <- exp(beta-1.96*mrTab$se)


mrTab$or_uci95Drug <- exp(beta+1.96*mrTab$se)

write.csv(mrTab, file="table.MRresult.csv", row.names=F)

heterTab <- mr_heterogeneity(dat)
write.csv(heterTab, file="table.heterogeneity.csv", row.names=F)

pleioTab <- mr_pleiotropy_test(dat)
write.csv(pleioTab, file="table.pleiotropy.csv", row.names=F)

pdf(file="pic.scatter_plot.pdf", width=7.5, height=7)
mr_scatter_plot(mrResult, dat)
dev.off()

res_single <- mr_singlesnp(dat)      #得到每个工具变量对结局的影响
pdf(file="pic.forest.pdf", width=7, height=5.5)
mr_forest_plot(res_single)
dev.off()

pdf(file="pic.funnel_plot.pdf", width=7, height=6.5)
mr_funnel_plot(singlesnp_results = res_single)
dev.off()

pdf(file="pic.leaveoneout.pdf", width=7, height=5.5)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
dev.off()

print("drugMR05 is done.")

```

**Comment by JasonQiu** [comment]
Thanks for sharing the commands you used. Our record shows that the most recent request you made successfully was for tophits of ieu-a-300 at 2024-07-22T13:05:29.755Z, so can I assume that the issue is resolved. Please let us know if the problem persists.

**Comment by dongchaoanderuni** [comment]
When I use prefix with "ukb" like "ukb-a-435", it will caused used up. I have no idea, why this occured. Play have a try. Thanks. And see my record. Thanks a lot.

**Comment by dongchaoanderuni** [comment]
> Thanks for sharing the commands you used. Our record shows that the most recent request you made successfully was for tophits of ieu-a-300 at 2024-07-22T13:05:29.755Z, so can I assume that the issue is resolved. Please let us know if the problem persists.

When I use prefix with "ukb" like "ukb-a-435", it will caused used up. I have no idea, why this occured. Play have a try. Thanks. And see my record. Thanks a lot.

**Comment by zyz-430** [comment]
Sorry to disturb,I have met the same problem. Despite only running a single gene analysis once, I have received a warning that my OpenGWAS allowance has been exhausted.I have suffered from it for almost one week.I'd appreciate it if you could help me with it.My Account lD of the token is:67628d02-7676-35f7-a0e7-4e69ec2b46ba
**the bug is as follows:**
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping ukb-a-435, 13024 variants, using EUR population reference
Warning in set_reset(r) :
  You have used up your OpenGWAS allowance. Your allowance will reset at 2024-07-22 23:27:13.37214. See https://api.opengwas.io/api/#allowance for more details.
No encoding supplied: defaulting to UTF-8.

Error in mtfrm.default(list(url = "https://api.opengwas.io/api/ld/clump",  (drugMR05.MR.R#50): cannot mtfrm
Show stack trace


**And here are the details of the gene analysis I conducted:**
exposureID="ukb-a-435" #暴露数据ID
outcomeID="ukb-d-I9_HYPTENS" #结局数据ID

geneChr=10 #基因所在的染色体(https://www.ncbi.nlm.nih.gov/gene)
geneStart=115803625 #染色体起始位置
geneEnd=115806663 #染色体终止位置

exposureName="Vascular/heart problems diagnosed by doctor: None of the above || ADRB1" #设置图形中展示暴露因素的名称
diseaseName="Hypertension" #疾病名称
setwd("D:\projects\0004_DrugTargetMR\05.MR") #设置工作目录

**Comment by JasonQiu** [comment]
> When I use prefix with "ukb" like "ukb-a-435", it will caused used up. I have no idea, why this occured. Play have a try. Thanks. And see my record. Thanks a lot.

Many thanks - that's very helpful.

```
> clumped <- clump_data(exposure_dat, clump_kb=100,
+                       clump_r2 = 0.3,
+                       clump_p1 = 5e-08,
+                       clump_p2 = 5e-08,
+                       pop = "EUR")
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping ukb-a-435, 13024 variants, using EUR population reference
Removing 12458 of 13024 variants due to LD with other variants or absence from LD reference panel
```

It turns out that the cost of /ld/clump was too high. It was set to N<sub>rsid</sub> * 10, so if you send e.g. 13024 variants in a request, it will cost you 130240. Since your allowance is 100000 per 10 minutes (at the time of writing), a single request like that will exhaust your allowance all of a sudden, and you won't even get the result from that request.

We have reviewed the logs and decided to lower the [cost](https://api.opengwas.io/api/#allowance) of /ld/clump to a fixed figure (regardless of N<sub>rsid</sub>). This has now come into effect but subject to change following further reviews.

Apologies for the inconvenience, and good luck!

P.S. On https://api.opengwas.io/profile/ page under Allowance, "Allowance" is what you can have (fixed) and "Remaining" is what you have left (updated real-time). Maybe run a few queries with TwoSampleMR and refresh this page to get a better understanding.
