### ISSUE TITLE
Meaning of variable "priority"

### ISSUE THREAD

**Issue by Owen-haha** [MRCIEU/TwoSampleMR#60]
Hi, 

I am wondering what is the meaning of "priority" on the outcome data.

Command `ao <- available_outcomes()` returns the detail of outcome data. There is a column named "**priority**", and its values can be zero or positive integer. 

May I know what does zero mean? Is it the smaller positive integer the higher priority? 

Thanks!

**Comment by explodecomputer** [comment]
Hi @Owen-haha thanks for the question. Because there are many duplicate traits we tried to provide an annotation that selected the 'best' study for a particular trait, this is the priority column. 1 means best, 0 means it hasn't been annotated. These annotations are not necessarily up-to-date and I wouldn't rely on them too much. @mightyphil2000 is there a better way that you were working on to select the best studies?

**Comment by mightyphil2000** [comment]
Hi @Owen-haha Sorry for my late reply. Thanks @explodecomputer. 

The priority column is used to indicate which study should be used from a set of duplicate studies (e.g. multiple GWAS of exactly the same phenotype from the same consortium) (1=best). This almost always corresponds to the larger study (or the one with more cases if a case-control study). "Best" basically means the study we expect to provide the highest statistical power for an MR analysis. However, sometimes the study with the largest sample size can have a relatively poor SNP coverage, e.g. if a fine mapping study or other targeted array study. For example in the IGAP studies of Alzheimer's disease, the priority value of 1 corresponds to the second largest study because it has a much higher SNP coverage than the study with the most cases. The latter example was the motivation for creating the priority column in the first place. However, I would say that the priority column has been made redundant by the power.prune function. The power.prune function selects the harmonised dataset - the output from harmonise_data() - which we expect to have the highest statistical power for the MR analysis being undertaken. This will either be based on the sample size or will take into account both sample size and the instrumental SNPs available. In theory, sometimes the study with the smaller sample size could have higher power if the number of instrumental SNPs available is highly heterogenous between datasets (e.g. is much higher in the second largest study). I would recommend you use either the power.prune function or that you simply select the duplicate study with the largest sample size (which should give similar results to the power.prune function most of the time). 

Hope this helps.
